#!/usr/bin/env node
// Adds the `ui` dictionary block: every user-visible string that was still
// hard-coded in English inside shared components (PromoBanner, PartnerStack,
// JobsCTA, SlateRemoteBanner, FaqSection, FeaturedPartners) and in page-level
// headings. Those render on ~5200 pages x 6 non-English locales, which left
// most of the site reading half-English.
import { readFileSync, writeFileSync } from 'node:fs';

const UI = {
  en: {
    sponsored: 'Sponsored',
    promo: {
      setup: { eyebrow: 'Before you board the flight', headline: 'Open a multi-currency account in 2 minutes', cta: 'Get Wise (free)' },
      insurance: { eyebrow: 'Travel insurance for nomads', headline: 'From $45/mo. Covers 175+ countries. Cancel anytime.', cta: 'See SafetyWing plans' },
      banking: { eyebrow: 'Spend abroad without fees', headline: 'Revolut: real exchange rate, virtual cards, free EU IBAN', cta: 'Open Revolut' },
      esim: { eyebrow: 'Land with data already on', headline: 'eSIM for 200+ countries. $3 off with code SACHA6010.', cta: 'Get Airalo eSIM' },
      vpn: { eyebrow: 'Hotel wifi is a minefield', headline: 'NordVPN: 6 devices, 60+ countries, kill switch', cta: 'Get NordVPN' },
      ai: { eyebrow: 'Your remote-work copilot', headline: 'Claude: long-form research, writing, and code from anywhere', cta: 'Try Claude' },
    },
    partnerStackHeading: 'Useful for this trip',
    featuredPartnersHeading: 'Set up in 2 minutes',
    faqHeading: 'Frequently asked',
    jobs: {
      sisterSite: 'Sister site', browseOn: 'Browse on', searchJobs: 'Search jobs on Slate Remote',
      perks: 'Free · No signup · Updated daily',
      headlineRole: 'Every remote {role} job, in one place',
      headlineCountry: 'Remote jobs you can do from {country}',
      headlineGeneric: 'The remote job, wherever you are',
      sublineRole: 'Slate Remote aggregates every remote {role} role from across the web. One search, every source — refreshed daily.',
      sublineCountry: 'Slate Remote pulls remote roles from every major board. Filter by country, role, time zone — find the job that lets you stay in {country}.',
      sublineGeneric: 'Slate Remote aggregates remote roles from every major job board. One search across all sources, refreshed daily — so you can pick a city on Slowmadly and a job on Slate Remote.',
      ctaCity: 'Looking for work in {name}? Browse open remote roles.',
      ctaCountry: 'Working remote from {country}? See open positions.',
      ctaGeneric: 'Need a remote tech job?',
    },
    headings: {
      coworkingTools: 'Tools we use on coworking days',
      setupBeforeApply: 'Set up before you apply',
      toolsSlowTravel: 'Tools to fund the slow-travel life',
      dailyCosts: 'Daily costs add up — here’s what helps',
      jobToFund: 'Need a remote job to fund {name}?',
      remoteRolesPair: 'Remote roles in {a} or {b}?',
      remoteRolesAcross: 'Remote roles across {name}',
      remoteJobFor: 'Remote job for {name}? See sister site.',
      workingFrom: 'Working from {name}',
    },
    page: {
      notFoundBody: 'The page you are looking for does not exist or has moved.',
      filterByPassport: 'Filter by your passport',
      forNomads2026: 'For digital nomads in 2026.',
      costIndexLabel: 'Cost of living index',
      forRolesIntro: 'Best digital nomad cities curated for your specific job.',
      citiesAtBest: 'Cities at their best',
      countriesToBase: 'Countries to base in',
      seasonalIntro: 'Time the world. Pick destinations that are at their best when you visit.',
      affiliateDisclosure: 'Affiliate disclosure',
      maxCostIndex: 'Max cost index',
      minNomadScore: 'Min nomad score',
    },
  },
  fr: {
    sponsored: 'Sponsorisé',
    promo: {
      setup: { eyebrow: 'Avant de monter dans l’avion', headline: 'Ouvrez un compte multidevise en 2 minutes', cta: 'Obtenir Wise (gratuit)' },
      insurance: { eyebrow: 'Assurance voyage pour nomades', headline: 'Dès 45 $/mois. Couvre 175+ pays. Annulable à tout moment.', cta: 'Voir les offres SafetyWing' },
      banking: { eyebrow: 'Dépensez à l’étranger sans frais', headline: 'Revolut : taux réel, cartes virtuelles, IBAN européen gratuit', cta: 'Ouvrir Revolut' },
      esim: { eyebrow: 'Atterrissez déjà connecté', headline: 'eSIM pour 200+ pays. 3 $ de remise avec le code SACHA6010.', cta: 'Obtenir l’eSIM Airalo' },
      vpn: { eyebrow: 'Le wifi d’hôtel est un champ de mines', headline: 'NordVPN : 6 appareils, 60+ pays, kill switch', cta: 'Obtenir NordVPN' },
      ai: { eyebrow: 'Votre copilote de travail à distance', headline: 'Claude : recherche, rédaction et code depuis n’importe où', cta: 'Essayer Claude' },
    },
    partnerStackHeading: 'Utile pour ce voyage',
    featuredPartnersHeading: 'Prêt en 2 minutes',
    faqHeading: 'Questions fréquentes',
    jobs: {
      sisterSite: 'Site partenaire', browseOn: 'Voir sur', searchJobs: 'Chercher un job sur Slate Remote',
      perks: 'Gratuit · Sans inscription · Mis à jour chaque jour',
      headlineRole: 'Tous les postes {role} en remote, au même endroit',
      headlineCountry: 'Des jobs remote que vous pouvez faire depuis {country}',
      headlineGeneric: 'Le job remote, où que vous soyez',
      sublineRole: 'Slate Remote regroupe toutes les offres {role} en remote du web. Une seule recherche, toutes les sources — actualisées chaque jour.',
      sublineCountry: 'Slate Remote agrège les offres remote de tous les grands job boards. Filtrez par pays, poste, fuseau — et trouvez le job qui vous permet de rester à {country}.',
      sublineGeneric: 'Slate Remote agrège les offres remote de tous les grands job boards. Une recherche sur toutes les sources, actualisée chaque jour — choisissez une ville sur Slowmadly et un job sur Slate Remote.',
      ctaCity: 'Vous cherchez du travail à {name} ? Parcourez les offres remote.',
      ctaCountry: 'Vous travaillez à distance depuis {country} ? Voir les postes ouverts.',
      ctaGeneric: 'Besoin d’un job tech en remote ?',
    },
    headings: {
      coworkingTools: 'Ce qu’on utilise les jours de coworking',
      setupBeforeApply: 'À préparer avant de déposer votre dossier',
      toolsSlowTravel: 'Des outils pour financer le voyage lent',
      dailyCosts: 'Les frais du quotidien s’accumulent — voici ce qui aide',
      jobToFund: 'Besoin d’un job remote pour financer {name} ?',
      remoteRolesPair: 'Des postes remote à {a} ou {b} ?',
      remoteRolesAcross: 'Des postes remote partout en {name}',
      remoteJobFor: 'Un job remote pour {name} ? Voir le site partenaire.',
      workingFrom: 'Travailler depuis {name}',
    },
    page: {
      notFoundBody: 'La page que vous cherchez n’existe pas ou a été déplacée.',
      filterByPassport: 'Filtrer selon votre passeport',
      forNomads2026: 'Pour les nomades numériques en 2026.',
      costIndexLabel: 'Indice du coût de la vie',
      forRolesIntro: 'Les meilleures villes pour nomades, sélectionnées selon votre métier.',
      citiesAtBest: 'Les villes à leur meilleur',
      countriesToBase: 'Des pays où s’installer',
      seasonalIntro: 'Suivez les saisons. Choisissez des destinations au meilleur moment de leur année.',
      affiliateDisclosure: 'Transparence sur l’affiliation',
      maxCostIndex: 'Indice de coût max',
      minNomadScore: 'Score nomade min',
    },
  },
  es: {
    sponsored: 'Patrocinado',
    promo: {
      setup: { eyebrow: 'Antes de subir al avión', headline: 'Abre una cuenta multidivisa en 2 minutos', cta: 'Consigue Wise (gratis)' },
      insurance: { eyebrow: 'Seguro de viaje para nómadas', headline: 'Desde 45 $/mes. Cubre 175+ países. Cancela cuando quieras.', cta: 'Ver planes de SafetyWing' },
      banking: { eyebrow: 'Gasta en el extranjero sin comisiones', headline: 'Revolut: tipo de cambio real, tarjetas virtuales, IBAN europeo gratis', cta: 'Abrir Revolut' },
      esim: { eyebrow: 'Aterriza ya con datos', headline: 'eSIM para 200+ países. 3 $ de descuento con el código SACHA6010.', cta: 'Consigue la eSIM de Airalo' },
      vpn: { eyebrow: 'El wifi de hotel es un campo minado', headline: 'NordVPN: 6 dispositivos, 60+ países, kill switch', cta: 'Consigue NordVPN' },
      ai: { eyebrow: 'Tu copiloto de trabajo remoto', headline: 'Claude: investigación, redacción y código desde cualquier sitio', cta: 'Probar Claude' },
    },
    partnerStackHeading: 'Útil para este viaje',
    featuredPartnersHeading: 'Listo en 2 minutos',
    faqHeading: 'Preguntas frecuentes',
    jobs: {
      sisterSite: 'Sitio hermano', browseOn: 'Ver en', searchJobs: 'Buscar empleo en Slate Remote',
      perks: 'Gratis · Sin registro · Actualizado a diario',
      headlineRole: 'Todos los empleos remotos de {role}, en un solo sitio',
      headlineCountry: 'Empleos remotos que puedes hacer desde {country}',
      headlineGeneric: 'El empleo remoto, estés donde estés',
      sublineRole: 'Slate Remote reúne todas las ofertas remotas de {role} de la web. Una búsqueda, todas las fuentes — actualizadas a diario.',
      sublineCountry: 'Slate Remote agrega ofertas remotas de los principales portales. Filtra por país, puesto y huso horario — y encuentra el empleo que te permite quedarte en {country}.',
      sublineGeneric: 'Slate Remote agrega ofertas remotas de todos los grandes portales. Una búsqueda en todas las fuentes, actualizada a diario — elige ciudad en Slowmadly y empleo en Slate Remote.',
      ctaCity: '¿Buscas trabajo en {name}? Explora las ofertas remotas.',
      ctaCountry: '¿Trabajas en remoto desde {country}? Mira las vacantes.',
      ctaGeneric: '¿Necesitas un empleo tech en remoto?',
    },
    headings: {
      coworkingTools: 'Lo que usamos en los días de coworking',
      setupBeforeApply: 'Prepáralo antes de solicitar',
      toolsSlowTravel: 'Herramientas para financiar el viaje lento',
      dailyCosts: 'Los gastos diarios suman — esto es lo que ayuda',
      jobToFund: '¿Necesitas un empleo remoto para financiar {name}?',
      remoteRolesPair: '¿Puestos remotos en {a} o {b}?',
      remoteRolesAcross: 'Puestos remotos por todo {name}',
      remoteJobFor: '¿Un empleo remoto para {name}? Mira el sitio hermano.',
      workingFrom: 'Trabajar desde {name}',
    },
    page: {
      notFoundBody: 'La página que buscas no existe o se ha movido.',
      filterByPassport: 'Filtra por tu pasaporte',
      forNomads2026: 'Para nómadas digitales en 2026.',
      costIndexLabel: 'Índice de coste de vida',
      forRolesIntro: 'Las mejores ciudades para nómadas, elegidas según tu profesión.',
      citiesAtBest: 'Ciudades en su mejor momento',
      countriesToBase: 'Países donde establecerte',
      seasonalIntro: 'Sigue las estaciones. Elige destinos en su mejor momento del año.',
      affiliateDisclosure: 'Aviso de afiliación',
      maxCostIndex: 'Índice de coste máx.',
      minNomadScore: 'Puntuación nómada mín.',
    },
  },
  pt: {
    sponsored: 'Patrocinado',
    promo: {
      setup: { eyebrow: 'Antes de entrar no avião', headline: 'Abra uma conta multimoeda em 2 minutos', cta: 'Obter o Wise (grátis)' },
      insurance: { eyebrow: 'Seguro de viagem para nómadas', headline: 'A partir de 45 $/mês. Cobre 175+ países. Cancele quando quiser.', cta: 'Ver planos SafetyWing' },
      banking: { eyebrow: 'Gaste no estrangeiro sem comissões', headline: 'Revolut: câmbio real, cartões virtuais, IBAN europeu grátis', cta: 'Abrir o Revolut' },
      esim: { eyebrow: 'Aterre já com dados', headline: 'eSIM para 200+ países. 3 $ de desconto com o código SACHA6010.', cta: 'Obter o eSIM Airalo' },
      vpn: { eyebrow: 'O wifi de hotel é um campo minado', headline: 'NordVPN: 6 dispositivos, 60+ países, kill switch', cta: 'Obter o NordVPN' },
      ai: { eyebrow: 'O seu copiloto de trabalho remoto', headline: 'Claude: pesquisa, escrita e código a partir de qualquer lugar', cta: 'Experimentar o Claude' },
    },
    partnerStackHeading: 'Útil para esta viagem',
    featuredPartnersHeading: 'Pronto em 2 minutos',
    faqHeading: 'Perguntas frequentes',
    jobs: {
      sisterSite: 'Site parceiro', browseOn: 'Ver em', searchJobs: 'Procurar emprego no Slate Remote',
      perks: 'Grátis · Sem registo · Atualizado diariamente',
      headlineRole: 'Todas as vagas remotas de {role}, num só lugar',
      headlineCountry: 'Empregos remotos que pode fazer a partir de {country}',
      headlineGeneric: 'O emprego remoto, onde quer que esteja',
      sublineRole: 'O Slate Remote reúne todas as vagas remotas de {role} da web. Uma pesquisa, todas as fontes — atualizadas diariamente.',
      sublineCountry: 'O Slate Remote agrega vagas remotas dos principais portais. Filtre por país, função e fuso — e encontre o emprego que o deixa ficar em {country}.',
      sublineGeneric: 'O Slate Remote agrega vagas remotas de todos os grandes portais. Uma pesquisa em todas as fontes, atualizada diariamente — escolha a cidade no Slowmadly e o emprego no Slate Remote.',
      ctaCity: 'À procura de trabalho em {name}? Veja as vagas remotas.',
      ctaCountry: 'Trabalha remotamente a partir de {country}? Veja as vagas abertas.',
      ctaGeneric: 'Precisa de um emprego tech remoto?',
    },
    headings: {
      coworkingTools: 'O que usamos nos dias de coworking',
      setupBeforeApply: 'Prepare antes de se candidatar',
      toolsSlowTravel: 'Ferramentas para financiar a viagem lenta',
      dailyCosts: 'Os custos diários somam — eis o que ajuda',
      jobToFund: 'Precisa de um emprego remoto para financiar {name}?',
      remoteRolesPair: 'Vagas remotas em {a} ou {b}?',
      remoteRolesAcross: 'Vagas remotas por todo o {name}',
      remoteJobFor: 'Um emprego remoto para {name}? Veja o site parceiro.',
      workingFrom: 'Trabalhar a partir de {name}',
    },
    page: {
      notFoundBody: 'A página que procura não existe ou foi movida.',
      filterByPassport: 'Filtre pelo seu passaporte',
      forNomads2026: 'Para nómadas digitais em 2026.',
      costIndexLabel: 'Índice de custo de vida',
      forRolesIntro: 'As melhores cidades para nómadas, escolhidas segundo a sua profissão.',
      citiesAtBest: 'Cidades no seu melhor',
      countriesToBase: 'Países onde se instalar',
      seasonalIntro: 'Siga as estações. Escolha destinos no melhor momento do ano.',
      affiliateDisclosure: 'Aviso de afiliação',
      maxCostIndex: 'Índice de custo máx.',
      minNomadScore: 'Pontuação nómada mín.',
    },
  },
  it: {
    sponsored: 'Sponsorizzato',
    promo: {
      setup: { eyebrow: 'Prima di salire sull’aereo', headline: 'Apri un conto multivaluta in 2 minuti', cta: 'Ottieni Wise (gratis)' },
      insurance: { eyebrow: 'Assicurazione viaggio per nomadi', headline: 'Da 45 $/mese. Copre 175+ paesi. Disdici quando vuoi.', cta: 'Vedi i piani SafetyWing' },
      banking: { eyebrow: 'Spendi all’estero senza commissioni', headline: 'Revolut: cambio reale, carte virtuali, IBAN europeo gratuito', cta: 'Apri Revolut' },
      esim: { eyebrow: 'Atterra già connesso', headline: 'eSIM per 200+ paesi. 3 $ di sconto col codice SACHA6010.', cta: 'Ottieni l’eSIM Airalo' },
      vpn: { eyebrow: 'Il wifi degli hotel è un campo minato', headline: 'NordVPN: 6 dispositivi, 60+ paesi, kill switch', cta: 'Ottieni NordVPN' },
      ai: { eyebrow: 'Il tuo copilota per il lavoro da remoto', headline: 'Claude: ricerca, scrittura e codice da qualsiasi posto', cta: 'Prova Claude' },
    },
    partnerStackHeading: 'Utile per questo viaggio',
    featuredPartnersHeading: 'Pronto in 2 minuti',
    faqHeading: 'Domande frequenti',
    jobs: {
      sisterSite: 'Sito gemello', browseOn: 'Guarda su', searchJobs: 'Cerca lavoro su Slate Remote',
      perks: 'Gratis · Senza registrazione · Aggiornato ogni giorno',
      headlineRole: 'Tutte le offerte da remoto per {role}, in un solo posto',
      headlineCountry: 'Lavori da remoto che puoi fare da {country}',
      headlineGeneric: 'Il lavoro da remoto, ovunque tu sia',
      sublineRole: 'Slate Remote raccoglie tutte le offerte da remoto per {role} dal web. Una ricerca, tutte le fonti — aggiornate ogni giorno.',
      sublineCountry: 'Slate Remote aggrega offerte da remoto da tutti i principali portali. Filtra per paese, ruolo e fuso — e trova il lavoro che ti fa restare in {country}.',
      sublineGeneric: 'Slate Remote aggrega offerte da remoto da tutti i grandi portali. Una ricerca su tutte le fonti, aggiornata ogni giorno — scegli la città su Slowmadly e il lavoro su Slate Remote.',
      ctaCity: 'Cerchi lavoro a {name}? Guarda le offerte da remoto.',
      ctaCountry: 'Lavori da remoto dall’{country}? Guarda le posizioni aperte.',
      ctaGeneric: 'Ti serve un lavoro tech da remoto?',
    },
    headings: {
      coworkingTools: 'Cosa usiamo nei giorni di coworking',
      setupBeforeApply: 'Prepara tutto prima di fare domanda',
      toolsSlowTravel: 'Strumenti per finanziare il viaggio lento',
      dailyCosts: 'Le spese quotidiane si sommano — ecco cosa aiuta',
      jobToFund: 'Ti serve un lavoro da remoto per finanziare {name}?',
      remoteRolesPair: 'Posizioni da remoto a {a} o {b}?',
      remoteRolesAcross: 'Posizioni da remoto in tutta {name}',
      remoteJobFor: 'Un lavoro da remoto per {name}? Guarda il sito gemello.',
      workingFrom: 'Lavorare da {name}',
    },
    page: {
      notFoundBody: 'La pagina che cerchi non esiste o è stata spostata.',
      filterByPassport: 'Filtra per il tuo passaporto',
      forNomads2026: 'Per i nomadi digitali nel 2026.',
      costIndexLabel: 'Indice del costo della vita',
      forRolesIntro: 'Le migliori città per nomadi, scelte in base al tuo lavoro.',
      citiesAtBest: 'Città al loro meglio',
      countriesToBase: 'Paesi in cui stabilirsi',
      seasonalIntro: 'Segui le stagioni. Scegli destinazioni nel loro momento migliore dell’anno.',
      affiliateDisclosure: 'Informativa sull’affiliazione',
      maxCostIndex: 'Indice di costo max',
      minNomadScore: 'Punteggio nomade min',
    },
  },
  de: {
    sponsored: 'Anzeige',
    promo: {
      setup: { eyebrow: 'Bevor du ins Flugzeug steigst', headline: 'Eröffne in 2 Minuten ein Multiwährungskonto', cta: 'Wise holen (kostenlos)' },
      insurance: { eyebrow: 'Reiseversicherung für Nomaden', headline: 'Ab 45 $/Monat. Deckt 175+ Länder. Jederzeit kündbar.', cta: 'SafetyWing-Tarife ansehen' },
      banking: { eyebrow: 'Im Ausland zahlen ohne Gebühren', headline: 'Revolut: echter Wechselkurs, virtuelle Karten, kostenlose EU-IBAN', cta: 'Revolut eröffnen' },
      esim: { eyebrow: 'Lande mit aktiven Daten', headline: 'eSIM für 200+ Länder. 3 $ Rabatt mit Code SACHA6010.', cta: 'Airalo-eSIM holen' },
      vpn: { eyebrow: 'Hotel-WLAN ist ein Minenfeld', headline: 'NordVPN: 6 Geräte, 60+ Länder, Kill Switch', cta: 'NordVPN holen' },
      ai: { eyebrow: 'Dein Copilot fürs Remote-Arbeiten', headline: 'Claude: Recherche, Texte und Code von überall', cta: 'Claude testen' },
    },
    partnerStackHeading: 'Nützlich für diese Reise',
    featuredPartnersHeading: 'In 2 Minuten startklar',
    faqHeading: 'Häufige Fragen',
    jobs: {
      sisterSite: 'Schwesterseite', browseOn: 'Ansehen auf', searchJobs: 'Jobs auf Slate Remote suchen',
      perks: 'Kostenlos · Ohne Anmeldung · Täglich aktualisiert',
      headlineRole: 'Alle Remote-Jobs als {role} an einem Ort',
      headlineCountry: 'Remote-Jobs, die du aus {country} machen kannst',
      headlineGeneric: 'Der Remote-Job, wo immer du bist',
      sublineRole: 'Slate Remote bündelt alle Remote-Stellen als {role} aus dem ganzen Web. Eine Suche, alle Quellen — täglich aktualisiert.',
      sublineCountry: 'Slate Remote bündelt Remote-Stellen von allen großen Jobbörsen. Filtere nach Land, Rolle und Zeitzone — und finde den Job, mit dem du in {country} bleiben kannst.',
      sublineGeneric: 'Slate Remote bündelt Remote-Stellen von allen großen Jobbörsen. Eine Suche über alle Quellen, täglich aktualisiert — such dir die Stadt auf Slowmadly und den Job auf Slate Remote.',
      ctaCity: 'Auf Jobsuche in {name}? Sieh dir die Remote-Stellen an.',
      ctaCountry: 'Du arbeitest remote aus {country}? Sieh dir offene Stellen an.',
      ctaGeneric: 'Brauchst du einen Remote-Tech-Job?',
    },
    headings: {
      coworkingTools: 'Was wir an Coworking-Tagen nutzen',
      setupBeforeApply: 'Vor dem Antrag einrichten',
      toolsSlowTravel: 'Tools, die das langsame Reisen finanzieren',
      dailyCosts: 'Die täglichen Kosten summieren sich — das hilft',
      jobToFund: 'Brauchst du einen Remote-Job, um {name} zu finanzieren?',
      remoteRolesPair: 'Remote-Stellen in {a} oder {b}?',
      remoteRolesAcross: 'Remote-Stellen in ganz {name}',
      remoteJobFor: 'Ein Remote-Job für {name}? Sieh dir die Schwesterseite an.',
      workingFrom: 'Arbeiten aus {name}',
    },
    page: {
      notFoundBody: 'Die gesuchte Seite existiert nicht oder wurde verschoben.',
      filterByPassport: 'Nach deinem Reisepass filtern',
      forNomads2026: 'Für digitale Nomaden 2026.',
      costIndexLabel: 'Lebenshaltungskosten-Index',
      forRolesIntro: 'Die besten Nomadenstädte, ausgewählt nach deinem Beruf.',
      citiesAtBest: 'Städte in Bestform',
      countriesToBase: 'Länder zum Niederlassen',
      seasonalIntro: 'Reise mit den Jahreszeiten. Wähle Ziele, wenn sie am schönsten sind.',
      affiliateDisclosure: 'Hinweis zu Affiliate-Links',
      maxCostIndex: 'Max. Kostenindex',
      minNomadScore: 'Min. Nomaden-Score',
    },
  },
  pl: {
    sponsored: 'Materiał sponsorowany',
    promo: {
      setup: { eyebrow: 'Zanim wsiądziesz do samolotu', headline: 'Załóż konto wielowalutowe w 2 minuty', cta: 'Weź Wise (za darmo)' },
      insurance: { eyebrow: 'Ubezpieczenie podróżne dla nomadów', headline: 'Od 45 $/mies. Obejmuje 175+ krajów. Anuluj kiedy chcesz.', cta: 'Zobacz plany SafetyWing' },
      banking: { eyebrow: 'Płać za granicą bez prowizji', headline: 'Revolut: prawdziwy kurs, karty wirtualne, darmowy europejski IBAN', cta: 'Załóż Revolut' },
      esim: { eyebrow: 'Ląduj z już działającym internetem', headline: 'eSIM na 200+ krajów. 3 $ zniżki z kodem SACHA6010.', cta: 'Weź eSIM Airalo' },
      vpn: { eyebrow: 'Hotelowe wifi to pole minowe', headline: 'NordVPN: 6 urządzeń, 60+ krajów, kill switch', cta: 'Weź NordVPN' },
      ai: { eyebrow: 'Twój drugi pilot w pracy zdalnej', headline: 'Claude: research, pisanie i kod z dowolnego miejsca', cta: 'Wypróbuj Claude' },
    },
    partnerStackHeading: 'Przyda się w tej podróży',
    featuredPartnersHeading: 'Gotowe w 2 minuty',
    faqHeading: 'Najczęstsze pytania',
    jobs: {
      sisterSite: 'Serwis siostrzany', browseOn: 'Zobacz na', searchJobs: 'Szukaj pracy na Slate Remote',
      perks: 'Za darmo · Bez rejestracji · Aktualizowane codziennie',
      headlineRole: 'Wszystkie zdalne oferty dla {role} w jednym miejscu',
      headlineCountry: 'Praca zdalna, którą wykonasz z kraju {country}',
      headlineGeneric: 'Praca zdalna, gdziekolwiek jesteś',
      sublineRole: 'Slate Remote zbiera wszystkie zdalne oferty dla {role} z sieci. Jedno wyszukiwanie, wszystkie źródła — odświeżane codziennie.',
      sublineCountry: 'Slate Remote agreguje zdalne oferty z największych portali. Filtruj po kraju, roli i strefie czasowej — i znajdź pracę, dzięki której zostaniesz w kraju {country}.',
      sublineGeneric: 'Slate Remote agreguje zdalne oferty ze wszystkich dużych portali. Jedno wyszukiwanie po wszystkich źródłach, odświeżane codziennie — wybierz miasto na Slowmadly, a pracę na Slate Remote.',
      ctaCity: 'Szukasz pracy w {name}? Przejrzyj zdalne oferty.',
      ctaCountry: 'Pracujesz zdalnie z kraju {country}? Zobacz otwarte rekrutacje.',
      ctaGeneric: 'Potrzebujesz zdalnej pracy w IT?',
    },
    headings: {
      coworkingTools: 'Czego używamy w dni coworkingowe',
      setupBeforeApply: 'Przygotuj przed złożeniem wniosku',
      toolsSlowTravel: 'Narzędzia, które sfinansują powolne podróżowanie',
      dailyCosts: 'Codzienne koszty się sumują — oto co pomaga',
      jobToFund: 'Potrzebujesz zdalnej pracy, by sfinansować {name}?',
      remoteRolesPair: 'Zdalne role w {a} czy {b}?',
      remoteRolesAcross: 'Zdalne role w całym regionie {name}',
      remoteJobFor: 'Zdalna praca dla {name}? Zobacz serwis siostrzany.',
      workingFrom: 'Praca z {name}',
    },
    page: {
      notFoundBody: 'Strona, której szukasz, nie istnieje lub została przeniesiona.',
      filterByPassport: 'Filtruj według swojego paszportu',
      forNomads2026: 'Dla cyfrowych nomadów w 2026.',
      costIndexLabel: 'Indeks kosztów życia',
      forRolesIntro: 'Najlepsze miasta dla nomadów, dobrane pod Twój zawód.',
      citiesAtBest: 'Miasta w najlepszej formie',
      countriesToBase: 'Kraje na bazę',
      seasonalIntro: 'Podróżuj z porami roku. Wybieraj kierunki wtedy, gdy są najpiękniejsze.',
      affiliateDisclosure: 'Informacja o afiliacji',
      maxCostIndex: 'Maks. indeks kosztów',
      minNomadScore: 'Min. ocena nomady',
    },
  },
};

for (const [locale, block] of Object.entries(UI)) {
  const path = `locales/${locale}.json`;
  const dict = JSON.parse(readFileSync(path, 'utf8'));
  dict.ui = block;
  writeFileSync(path, JSON.stringify(dict, null, 2) + '\n');
  console.log(`${locale}: ui block added`);
}
console.log('Done.');
